import sys
import networkx as nx
import matplotlib.pyplot as plt

def main():
    # Check if the filename was passed from C++
    if len(sys.argv) < 2:
        print("Usage: python visualizer.py <mst_output_file>")
        return

    filename = sys.argv[1]
    
    # Initialize an undirected graph
    G = nx.Graph()
    
    try:
        # Read the intermediate file generated by C++
        with open(filename, 'r') as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) == 3:
                    u, v, weight = parts
                    # Add the edges (using integers for node IDs to support custom graphs)
                    G.add_edge(int(u), int(v), weight=int(weight))
    except FileNotFoundError:
        print(f"Error: Could not find or open '{filename}'.")
        print("Make sure the C++ program generated it successfully.")
        return
        
    if G.number_of_edges() == 0:
        print("No edges found to visualize.")
        return

    # Calculate an aesthetically pleasing layout for the nodes
    # spring_layout uses a force-directed algorithm to prevent overlaps
    pos = nx.spring_layout(G, seed=42) 
    
    # Setup the plot window
    plt.figure(figsize=(8, 6))
    plt.title("Minimum Spanning Tree (Prim's Algorithm)", fontsize=14, fontweight='bold')
    
    # Draw the nodes (circles)
    nx.draw_networkx_nodes(G, pos, node_size=700, node_color='lightgreen', edgecolors='black')
    
    # Draw the edges (lines)
    nx.draw_networkx_edges(G, pos, width=2.0, alpha=0.7)
    
    # Draw the node labels (mapped to letters a, b, c...)
    node_labels = {node: chr(ord('a') + node) for node in G.nodes()}
    nx.draw_networkx_labels(G, pos, labels=node_labels, font_size=12, font_family='sans-serif', font_color='black')
    
    # Draw the edge weights
    edge_labels = nx.get_edge_attributes(G, 'weight')
    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, font_size=10, label_pos=0.5)
    
    # Hide the background axis grid
    plt.axis('off')
    plt.tight_layout()
    
    # Open the interactive window (blocks the script until the user closes the window)
    plt.show()

if __name__ == "__main__":
    main()